version: "2"
run:
  timeout: 5m
  go: ""
  build-tags: []
  allow-parallel-runners: false
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - gochecknoglobals
    - gocognit
    - protogetter
    - errorlint
    - unused
    - funlen
    - goconst
    - paralleltest
    - rowserrcheck
    - unconvert
    - mirror
    - unparam
    - govet
    - dupl
    - interfacebloat
    - intrange
    - sloglint
    - copyloopvar
    - gosec
    - nakedret
    - nilerr
    - contextcheck
    - prealloc
    - nolintlint
    - ineffassign
    - staticcheck
    - errname
    - maintidx
    - misspell
    - errchkjson
    - gocritic
    - gosmopolitan
    - musttag
    - perfsprint
    - zerologlint
    - cyclop
    - nilnil
    - noctx
    - revive
    - sqlclosecheck
    - testifylint
    - errcheck
    - bodyclose
    - exhaustruct
    - predeclared
    - nilnesserr
    - wastedassign
    - usetesting
    - gocyclo
    - durationcheck
    - forcetypeassert
    - gochecknoinits
    - reassign
    - wrapcheck
    - exhaustive
    - gochecksumtype
    - nestif
    - spancheck
    - loggercheck
    - recvcheck
    - thelper
    - ginkgolinter
formatters:
  enable:
    - golines
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
